In [1]:
# Using One v all classification with Gradient Descent Algorithm for Logistic Regression
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

In [2]:
# extracting the data
train_data = pd.read_csv("train.csv")
train_data.insert(9,'NEW',0)
# making a new feature for giving importance to NaN values
train_data['NEW']=np.where(train_data['Number_Weeks_Used'].isnull(),1,0)
train_data

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000001                      188          1          0   
1      F00000003                      209          1          0   
2      F00000004                      257          1          0   
3      F00000005                      257          1          1   
4      F00000006                      342          1          0   
...          ...                      ...        ...        ...   
88853  F00155935                     3337          1          0   
88854  F00155938                     3516          1          0   
88855  F00155939                     3516          1          0   
88856  F00155942                     3702          1          0   
88857  F00155945                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                0.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
88853                       2                 10               12.0   
88854                       2                 10               20.0   
88855                       2                 15               40.0   
88856                       2                 10               25.0   
88857                       2                 20               37.0   

       Number_Weeks_Quit  Season  NEW  Crop_Damage  
0                      0       1    0            0  
1                      0       2    0            1  
2                      0       2    0            1  
3                      0       2    0            1  
4                      0       2    0            1  
...                  ...     ...  ...          ...  
88853                 44       3    0            0  
88854                 38       1    0            0  
88855                  8       2    0            0  
88856                 18       3    0            0  
88857                  7       3    0            0  

[88858 rows x 11 columns]

In [3]:
# Replacing NaN values with random values taken from the same column
random_sam=train_data['Number_Weeks_Used'].dropna().sample(train_data['Number_Weeks_Used'].isnull().sum(),random_state=0)
random_sam.index=train_data[train_data['Number_Weeks_Used'].isnull()].index
train_data.loc[train_data['Number_Weeks_Used'].isnull(),'Number_Weeks_Used']=random_sam
# feature scaling to validate the eucleadin distance
train_data['Estimated_Insects_Count']=(train_data['Estimated_Insects_Count']-train_data['Estimated_Insects_Count'].mean())/train_data['Estimated_Insects_Count'].std()
train_data

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000001                -1.426316          1          0   
1      F00000003                -1.401583          1          0   
2      F00000004                -1.345049          1          0   
3      F00000005                -1.345049          1          1   
4      F00000006                -1.244937          1          0   
...          ...                      ...        ...        ...   
88853  F00155935                 2.282540          1          0   
88854  F00155938                 2.493364          1          0   
88855  F00155939                 2.493364          1          0   
88856  F00155942                 2.712433          1          0   
88857  F00155945                 2.939746          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                0.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
88853                       2                 10               12.0   
88854                       2                 10               20.0   
88855                       2                 15               40.0   
88856                       2                 10               25.0   
88857                       2                 20               37.0   

       Number_Weeks_Quit  Season  NEW  Crop_Damage  
0                      0       1    0            0  
1                      0       2    0            1  
2                      0       2    0            1  
3                      0       2    0            1  
4                      0       2    0            1  
...                  ...     ...  ...          ...  
88853                 44       3    0            0  
88854                 38       1    0            0  
88855                  8       2    0            0  
88856                 18       3    0            0  
88857                  7       3    0            0  

[88858 rows x 11 columns]

In [4]:
# extracting and making features for training and finding apt weights 
X = np.array(train_data.iloc[:,1:10])
one = np.ones((88858,1),dtype=float)
X = np.matrix(np.hstack((one,X)))
Y1 = np.array([train_data.iloc[:,10]])
Y1 = Y1.T
Y2 = Y1.copy()
Y3 = Y1.copy()
for i in range(88858):
    if Y1[i] == 0:
        Y1[i] = 1
    else:
        Y1[i] = 0
    if Y2[i] == 1:
        pass
    else:
        Y2[i] = 0
    if Y3[i] == 2:
        Y3[i] = 1
    else:
        Y3[i] = 0
Y1=np.matrix(Y1)
Y2=np.matrix(Y2)
Y3=np.matrix(Y3)
#Randomly initilaizing weights
Theta1 = np.matrix(np.ones((10,1)))
Theta2 = np.matrix(np.ones((10,1)))
Theta3 = np.matrix(np.ones((10,1)))

In [5]:
def GradDesc(x,y,theta):
    z = x*theta
    h = 1/(1 + np.exp(-z))
    alpha=0.0025
    lamb=100
# minimizing the cost function
    J=(alpha/88858)*(np.transpose(x)*(h-y))
    count=0
    while count<=7000:
    #changing weights to reach the minimum of cost function
        theta=theta*(1-alpha*lamb/88858)-J
        z = x*theta
        h = 1/(1 + np.exp(-z))
        J=(alpha/88858)*(np.transpose(x)*(h-y))
        count+=1
    return theta

In [6]:
#Predicting the values
Theta1=GradDesc(X,Y1,Theta1)
z1=X*Theta1
h1=1/(1+np.exp(-z1))
Theta2=GradDesc(X,Y2,Theta2)
z2=X*Theta2
h2=1/(1+np.exp(-z2))
Theta3=GradDesc(X,Y3,Theta3)
z3=X*Theta3
h3=1/(1+np.exp(-z3))

In [7]:
# finding the appropriate prediction using one vs all classification method
def maxval(a,b,c):
    if a>=b and a>=c:
        return 0
    if b>=a and b>=c:
        return 1
    if c>=a and c>=b:
        return 2
h = np.matrix(np.zeros((88858,1)))

In [8]:
for i in range(88858):
    h[i] = maxval(h1[i][0],h2[i][0],h3[i][0])
y_a=list(train_data['Crop_Damage'])
y_p=list(np.array(h,dtype=int).flatten())
# Confusion Matrix
print("Confusion Matrix : \n",confusion_matrix(y_a,y_p))    
        

Confusion Matrix : 
 [[73844   368    26]
 [11908   268   131]
 [ 2226    40    47]]


In [9]:
#reading the test data
test_data = pd.read_csv("test.csv")
test_data.insert(9,'NEW',0)
# making a new feature for giving importance to NaN values
test_data['NEW']=np.where(test_data['Number_Weeks_Used'].isnull(),1,0)
test_data

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                      188          1          1   
1      F00000007                      410          1          1   
2      F00000011                      626          1          0   
3      F00000013                      731          1          0   
4      F00000014                      789          0          0   
...          ...                      ...        ...        ...   
59305  F00155937                     3337          1          0   
59306  F00155940                     3516          1          0   
59307  F00155941                     3702          1          0   
59308  F00155943                     3702          1          0   
59309  F00155944                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                NaN   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
59305                       2                 20               34.0   
59306                       2                 20               32.0   
59307                       2                 10                NaN   
59308                       2                 10               28.0   
59309                       2                  5               52.0   

       Number_Weeks_Quit  Season  NEW  
0                      0       2    1  
1                      0       2    0  
2                      0       2    0  
3                      0       2    0  
4                      0       1    0  
...                  ...     ...  ...  
59305                 12       1    0  
59306                 10       2    0  
59307                 48       1    1  
59308                 17       2    0  
59309                  7       1    0  

[59310 rows x 10 columns]

In [10]:
# Replacing NaN values with random values taken from the same column
random_sam=test_data['Number_Weeks_Used'].dropna().sample(test_data['Number_Weeks_Used'].isnull().sum(),random_state=0)
random_sam.index=test_data[test_data['Number_Weeks_Used'].isnull()].index
test_data.loc[test_data['Number_Weeks_Used'].isnull(),'Number_Weeks_Used']=random_sam
# feature scaling to validate the eucleadin distance
test_data['Estimated_Insects_Count']=(test_data['Estimated_Insects_Count']-test_data['Estimated_Insects_Count'].mean())/test_data['Estimated_Insects_Count'].std()
test_data

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                -1.423331          1          1   
1      F00000007                -1.161978          1          1   
2      F00000011                -0.907689          1          0   
3      F00000013                -0.784076          1          0   
4      F00000014                -0.715794          0          0   
...          ...                      ...        ...        ...   
59305  F00155937                 2.283879          1          0   
59306  F00155940                 2.494610          1          0   
59307  F00155941                 2.713581          1          0   
59308  F00155943                 2.713581          1          0   
59309  F00155944                 2.940793          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0               30.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
59305                       2                 20               34.0   
59306                       2                 20               32.0   
59307                       2                 10               25.0   
59308                       2                 10               28.0   
59309                       2                  5               52.0   

       Number_Weeks_Quit  Season  NEW  
0                      0       2    1  
1                      0       2    0  
2                      0       2    0  
3                      0       2    0  
4                      0       1    0  
...                  ...     ...  ...  
59305                 12       1    0  
59306                 10       2    0  
59307                 48       1    1  
59308                 17       2    0  
59309                  7       1    0  

[59310 rows x 10 columns]

In [11]:
# making features for testing 
X1 = np.array(test_data.iloc[:,1:10])
one = np.ones((59310,1),dtype=float)
X1 = np.matrix(np.hstack((one,X1)))
#Predicting the values
Z1=X1*Theta1
H1=1/(1+np.exp(-Z1))
Z2=X1*Theta2
H2=1/(1+np.exp(-Z2))
Z3=X1*Theta3
H3=1/(1+np.exp(-Z3))

In [12]:
# finding the appropriate prediction using one vs all classification method
H = np.matrix(np.zeros((59310,1)))
for i in range(59310):
    H[i] = maxval(H1[i][0],H2[i][0],H3[i][0])
a=0
b=0
c=0
for i in range(59310):
    if H[i] == 0:
        a+=1
    if H[i] == 1:
        b+=1
    if H[i] == 2:
        c+=1
print("Predicted 0's : ",a)
print("Predicted 1's : ",b)
print("Predicted 2's : ",c)    

Predicted 0's :  58678
Predicted 1's :  479
Predicted 2's :  153
